import type { Metadata } from "next";
import { Geist_Mono } from 'next/font/google';
import { Toaster } from "@/app/_components/ui/sonner";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${geistMono.variable} antialiased`}>
        {children}
        <Toaster position="top-center" duration={3000} />
      </body>
    </html>
  );
}